language: node_js
env:
  - CXX="g++-4.8"
node_js:
  - "0.10"
  - "0.12"
  - "iojs-v2.3.0"
  - "iojs-v3.0.0"
  - "4"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - gcc-4.8
before_script:
  - npm install -g grunt-cli node-gyp mocha
services:
  - cassandra
